version: '3'

services:
    php:
        image: matthiasnoback/testing-playground-php:8.2
        build: docker/php/
        volumes:
            - ./:/app:cached
        environment:
            XDEBUG_CONFIG: "client_host=${DOCKER_HOST_NAME_OR_IP}"
        user: ${HOST_UID}:${HOST_GID}
        env_file:
            -   .env
        extra_hosts:
            - "host.docker.internal:host-gateway"

    composer:
        image: composer:latest
        volumes:
            - ./:/app:cached
        user: ${HOST_UID}:${HOST_GID}
        env_file:
            -   .env
